### ISSUE TITLE
[QAIT] Oxipay Payment Gateway> Close browser on success page> Order history is not generated for placed order at client side and admin side 

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-prestashop-1.6#21] opened 2017-05-23 11:50 UTC
**Observation:** 
Oxipay confirmation email is received to the end user however, Order history is not generated at client side and admin side.

**Steps to Replicate:**
Launch URL: http://ec2-54-252-200-135.ap-southeast-2.compute.amazonaws.com
Add any item to cart and enter a valid address.
Select OXIPAY as payment method
Login into oxipay with valid credentials.
Enter card details and click on confirm button.
Verify that application displays success message “your payment has been approved..”
Close the browser before it navigates to merchant store
Verify the result in Order detail at client side and admin side

**Actual Result:** Order history is not generated for placed order at client side and admin side 

**Acceptance Criteria:** Application should have order history at client side and admin side when Oxipay confirmation email is received by the user

**Screencast**: https://www.screencast.com/t/ORQdOYWe 

**Tech Stack Details:**
http://ec2-54-252-200-135.ap-southeast-2.compute.amazonaws.com 
http://ec2-54-252-200-135.ap-southeast-2.compute.amazonaws.com/administration
 
Username/Password
user@example.com/bitnami

**Comment by big89** [comment] 2017-05-24 04:35
Hello,

I think you are closing browser when user redirect to success page and its not updating order in client and admin side. Because order processing code logic is on success page redirection which get skipped by browser closed.

In that case you need to implement webhook/callback, which is a asynchronous payment response from gateway server to merchant server, which will update your order in database in background.

Thanks & Regards,
Bhagwan
[ Logicmaker ]

**Comment by hellotaotao** [comment] 2017-05-25 07:04
We believe this is an artefact of the test conditions. We have successfully replicated and confirmed this test case is working against our production environment.

**Closed by hellotaotao** 2017-05-25 07:04 UTC
